"""Implement bidirectional relationship between User and ToDo

Revision ID: 904d53711558
Revises: 93416d1b8ff4
Create Date: 2025-11-26 10:40:48.631581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904d53711558'
down_revision: Union[str, Sequence[str], None] = '93416d1b8ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
